# Generated by Django 5.1.5 on 2025-12-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='summary',
            new_name='profile',
        ),
    ]
