# Generated by Django 5.1.5 on 2025-12-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_rename_summary_resume_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='role',
            field=models.CharField(choices=[('backend', 'Backend Developer'), ('data_analyst', 'Data Analyst'), ('ai_engineer', 'AI Engineer')], default='backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
