# Generated by Django 5.1.5 on 2025-12-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_remove_resume_created_at_resume_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_summary',
            field=models.TextField(blank=True, help_text='Short professional summary shown at the top of the resume', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.CharField(blank=True, help_text='GitHub / LinkedIn / Portfolio link or username', max_length=255, null=True),
        ),
    ]
